# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tardis_portal", "0013_auto_20181002_1136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storagebox",
            name="max_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="storagebox",
            name="status",
            field=models.CharField(default=b"online", max_length=100),
        ),
    ]
