# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tardis_portal', '0015_dataset_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='created_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
