# Generated by Django 2.2.7 on 2019-11-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tardis_portal', '0018_make_default_storage_box_status_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='algorithm',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='datafile',
            name='checksum',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.RunSQL(
            "UPDATE tardis_portal_datafile SET checksum=md5sum, algorithm='md5' WHERE algorithm='' AND md5sum IS NOT NULL"
        ),
        migrations.RunSQL(
            "UPDATE tardis_portal_datafile SET checksum=sha512sum, algorithm='sha512' WHERE algorithm='' AND sha512sum IS NOT NULL"
        )
    ]
