# Generated by Django 3.2.7 on 2023-08-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tardis_portal', '0018_make_default_storage_box_status_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthentication',
            name='authenticationMethod',
            field=models.CharField(choices=[('ldap', 'Monash Authcate'), ('localdb', 'Local DB'), ('google', 'Google'), ('aaf', 'Australian Access Federation')], max_length=30),
        ),
    ]
