# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-18 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('tardis_portal', '0018_make_default_storage_box_status_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='institution_name',
            field=models.CharField(default='University of Auckland', max_length=400),
        ),
        migrations.AlterField(
            model_name='storagebox',
            name='django_storage_class',
            field=models.TextField(default='storages.backends.s3boto3.S3Boto3Storage'),
        ),
    ]
