# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-14 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers
import tardis.tardis_portal.models.dataset
import tardis.tardis_portal.models.experiment


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('tardis_portal', '0018_make_default_storage_box_status_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='dataset_id',
            field=models.CharField(default=tardis.tardis_portal.models.dataset.dataset_id_default, max_length=400, unique=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='internal_id',
            field=models.CharField(default=tardis.tardis_portal.models.experiment.experiment_internal_id_default, max_length=400, unique=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='project_id',
            field=models.CharField(default='No Project', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_id',
            field=models.CharField(default='No Instrument ID', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiment',
            name='institution_name',
            field=models.CharField(default='University of Auckland', max_length=400),
        ),
        migrations.AlterField(
            model_name='storagebox',
            name='django_storage_class',
            field=models.TextField(default='storages.backends.s3boto3.S3Boto3Storage'),
        ),
    ]
