# Generated by Django 3.2.4 on 2021-08-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tardis_portal', '0018_make_default_storage_box_status_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='institution_name',
            field=models.CharField(default='University of Auckland', max_length=400),
        ),
        migrations.AlterField(
            model_name='storagebox',
            name='django_storage_class',
            field=models.TextField(default='django.core.files.storage.FileSystemStorage'),
        ),
        migrations.AlterField(
            model_name='userauthentication',
            name='authenticationMethod',
            field=models.CharField(choices=[('localdb', 'Local DB'), ('ldap', 'LDAP')], max_length=30),
        ),
    ]
