# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-09 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tardis_portal', '0019_auto_20191219_1139'),
        ('tardis_portal', '0018_uoa_dataset'),
    ]

    operations = [
    ]
