# Generated by Django 2.2.10 on 2020-03-17 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tardis_portal', '0019_auto_20200214_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=255, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('locked', models.BooleanField(default=False)),
                ('public_access', models.PositiveSmallIntegerField(choices=[(1, 'No public access (hidden)'), (25, 'Ready to be released pending embargo expiry'), (50, 'Public Metadata only (no data file access)'), (100, 'Public')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='parametername',
            name='is_viewable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='orcid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='project_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tardis_portal.Project'),
        ),
    ]
