# Generated by Django 2.2.10 on 2020-03-17 02:25

from django.db import migrations, models
import django.db.models.deletion
import tardis.tardis_portal.models.parameters


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tardis_portal', '0020_auto_20200317_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafileparameter',
            name='sensitive_metadata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasetparameter',
            name='sensitive_metadata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experimentparameter',
            name='sensitive_metadata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrumentparameter',
            name='sensitive_metadata',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProjectParameterSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tardis_portal.Project')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tardis_portal.Schema')),
                ('storage_box', models.ManyToManyField(related_name='projectparametersets', to='tardis_portal.StorageBox')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
            bases=(models.Model, tardis.tardis_portal.models.parameters.ParameterSetManagerMixin),
        ),
        migrations.CreateModel(
            name='ProjectParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_value', models.TextField(blank=True, null=True)),
                ('numerical_value', models.FloatField(blank=True, db_index=True, null=True)),
                ('datetime_value', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('link_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sensitive_metadata', models.BooleanField(default=False)),
                ('link_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tardis_portal.ParameterName')),
                ('parameterset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tardis_portal.ProjectParameterSet')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
