# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-09 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tardis_portal', '0020_merge_20200210_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='institution_name',
            field=models.CharField(default='University of Auckland', max_length=400),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='project_id',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='storagebox',
            name='django_storage_class',
            field=models.TextField(default='storages.backends.s3boto3.S3Boto3Storage'),
        ),
    ]
