# Generated by Django 2.2.10 on 2020-03-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tardis_portal', '0022_auto_20200318_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectacl',
            name='canDownload',
            field=models.BooleanField(default=False),
        ),
    ]
