# Generated by Django 2.2.10 on 2020-03-31 03:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tardis_portal', '0025_auto_20200320_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schema',
            name='type',
            field=models.IntegerField(choices=[(11, 'Project schema'), (1, 'Experiment schema'), (2, 'Dataset schema'), (3, 'Datafile schema'), (5, 'Instrument schema'), (4, 'None')], default=1),
        ),
    ]
