# Generated by Django 2.2.10 on 2020-05-04 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tardis_portal', '0027_auto_20200501_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectacl',
            name='canSensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 3, 49, 43, 631810)),
        ),
    ]
