# Generated by Django 2.2.10 on 2020-05-07 02:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tardis_portal', '0027_auto_20200501_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='internal_id',
            new_name='raid',
        ),
        migrations.RenameField(
            model_name='schema',
            old_name='type',
            new_name='schema_type',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='sensitive',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='sensitive',
        ),
        migrations.RemoveField(
            model_name='parametername',
            name='is_searchable',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sensitive',
        ),
        migrations.AddField(
            model_name='facility',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tardis_portal.Institution'),
        ),
        migrations.AddField(
            model_name='objectacl',
            name='canSensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='experimentauthor',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tardis_portal.Institution'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_id',
            field=models.CharField(default='No ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='lead_researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 2, 7, 32, 168451)),
        ),
    ]
