# Generated by Django 2.2.10 on 2020-05-07 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tardis_portal', '0028_auto_20200507_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 2, 24, 57, 395705)),
        ),
    ]
