# Generated by Django 2.2.10 on 2020-05-07 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tardis_portal', '0031_auto_20200507_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 2, 28, 15, 187277)),
        ),
    ]
