# Generated by Django 2.2.10 on 2020-05-07 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tardis_portal', '0034_auto_20200507_1435'),
        ('tardis_portal', '0028_auto_20200507_1408'),
    ]

    operations = [
    ]
