# Generated by Django 2.2.10 on 2020-05-14 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tardis_portal', '0036_auto_20200508_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='project_model',
            new_name='project',
        ),
    ]
