# Generated by Django 2.2.10 on 2020-07-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('tardis_portal', '0038_auto_20200610_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupadmin',
            name='admin_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='admin_groups', to='auth.Group'),
        ),
    ]
