# Generated by Django 4.2.2 on 2023-08-02 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "tardis_portal",
            "0025_alter_datafileacl_group_alter_datafileacl_token_and_more",
        ),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("projects", "0002_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(default="Monash University", max_length=255),
        ),
        migrations.AlterField(
            model_name="projectacl",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="projectacl",
            name="token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="tardis_portal.token",
            ),
        ),
        migrations.AlterField(
            model_name="projectacl",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projectparameterset",
            name="storage_box",
            field=models.ManyToManyField(
                related_name="%(class)ss", to="tardis_portal.storagebox"
            ),
        ),
    ]
