# Generated by Django 3.2.4 on 2023-04-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_institution_name_alter_projectacl_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(
                default="The University of Auckland | Waipapa Taumata Rau",
                max_length=255,
            ),
        ),
    ]
