FROM mytardis/mytardis-base

# prebuilt wheels from django-build.yml
ADD wheelhouse /wheelhouse
RUN chown -R webapp:webapp /wheelhouse

WORKDIR /home/webapp

USER webapp
ENV WHEELHOUSE=/wheelhouse
ENV PIP_WHEEL_DIR=/wheelhouse
ENV PIP_FIND_LINKS=/wheelhouse

ENV DOCKER_BUILD true
RUN . /appenv/bin/activate; \
    pip install --no-index -f /wheelhouse -r requirements.txt
