FROM ubuntu:16.04

RUN mkdir -p /home/webapp
RUN groupadd -r webapp && useradd -r -g webapp webapp

ENV DEBIAN_FRONTEND noninteractive
RUN echo 'APT::Get::Assume-Yes "true";' > /etc/apt/apt.conf.d/90assumeyes

RUN apt-get update && apt-get install \
    -qy \
    -o APT::Install-Recommends=false \
    -o APT::Install-Suggests=false \
    git \
    libldap2-dev \
    libsasl2-dev \
    libssl-dev \
    libxml2-dev \
    libxslt1-dev \
    nodejs \
    npm \
    python-pip \
    python-virtualenv \
    virtualenvwrapper \
    libmagic-dev \
    libmagickwand-dev \
    && apt-get clean

RUN mkdir /appenv
RUN chown -R webapp:webapp /appenv

RUN chown -R webapp:webapp /home/webapp
USER webapp
RUN virtualenv --system-site-packages /appenv
RUN . /appenv/bin/activate; pip install -U -e "git+https://github.com/pypa/pip.git#egg=pip" wheel
COPY . /home/webapp/
USER root
