version: "2"
services:
  run:
    build:
      context: .
      dockerfile: Dockerfile-run
    image: mytardis/mytardis-run
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    image: mytardis/mytardis-test
    volumes:
      - ./tardis:/home/webapp/tardis
      - ./docs:/home/webapp/docs
    depends_on:
      - run
      - pg
      - mysql
    links:
      - pg
      - mysql
  pg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
