FROM mytardis/mytardis-base

# prebuilt wheels from django-build.yml
ADD wheelhouse /wheelhouse

USER webapp

WORKDIR /home/webapp

ENV DOCKER_BUILD true
RUN /appenv/bin/pip install --no-index -f /wheelhouse \
    -r requirements.txt \
    psycopg2 \
    MySQL-python

ENTRYPOINT ["scripts/docker-cmd.sh"]
