FROM mytardis/mytardis-run

USER root
RUN apt-get update && apt-get install \
    -qy \
    phantomjs
USER webapp

RUN . /appenv/bin/activate; \
    pip install --no-index -f /wheelhouse psycopg2 mysql-python
RUN . /appenv/bin/activate; \
    pip install coveralls codacy-coverage
VOLUME /home/webapp/tardis
VOLUME /home/webapp/docs

RUN mkdir -p var/store

CMD bash -c '. /appenv/bin/activate; source ./test.sh'
