FROM mytardis/mytardis-run

RUN . /appenv/bin/activate; \
    pip install coveralls codacy-coverage
VOLUME /home/webapp/tardis
VOLUME /home/webapp/docs

RUN mkdir -p var/store

ENTRYPOINT bash -c '. /appenv/bin/activate; source ./test.sh'
