FROM mytardis/mytardis-base

# prebuilt wheels from django-build.yml
ADD wheelhouse /wheelhouse

USER webapp

WORKDIR /home/webapp

ENV DOCKER_BUILD true
RUN . /appenv/bin/activate; \
    pip install --no-index -f /wheelhouse -r requirements.txt
EXPOSE 8000
CMD ["python","manage.py","runserver","0.0.0.0:8000"]