version: "2"
services:
  run:
    build:
      context: ..
      dockerfile: docker-ci/Dockerfile-run
    image: mytardis/mytardis-run
  test:
    build:
      context: ..
      dockerfile: docker-ci/Dockerfile-test
    image: mytardis/mytardis-test
    environment:
      ELASTICSEARCH_URL: 'http://localhost:9200'
    volumes:
      - ../tardis:/home/webapp/tardis
      - ../docs:/home/webapp/docs
    depends_on:
      - run
      #- pg
      - mysql
      #- es
    links:
      #- pg
      - mysql
      #- es
  #pg:
  #  image: postgres:9.6
  #  environment:
  #    POSTGRES_PASSWORD: postgres
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    command: --default-authentication-plugin=mysql_native_password
  #es:
  #  image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
  #  environment:
  #    - bootstrap.memory_lock=true
  #    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #    - discovery.type=single-node
  #  ports:
  #    - "9300:9300"
  #    - "9200:9200"