FROM ubuntu:20.04

RUN mkdir -p /home/webapp
RUN groupadd -r webapp && useradd -r -g webapp webapp

ENV DEBIAN_FRONTEND noninteractive
RUN echo 'APT::Get::Assume-Yes "true";' > /etc/apt/apt.conf.d/90assumeyes

# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LANG C.UTF-8

RUN apt-get update && apt-get install \
    -qy \
    -o APT::Install-Recommends=false \
    -o APT::Install-Suggests=false \
    curl \
    git \
    gnupg \
    libldap2-dev \
    libsasl2-dev \
    libssl-dev \
    libxml2-dev \
    libxslt1-dev \
    python3-pip \
    python3-dev \
    python3-venv \
    python3-setuptools \
    libmagic-dev \
    libmagickwand-dev \
    libmysqlclient20 \
    && apt-get clean

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs

RUN mkdir /appenv
RUN chown -R webapp:webapp /appenv

RUN chown -R webapp:webapp /home/webapp
USER webapp
RUN python3 -m venv /appenv
RUN . /appenv/bin/activate; pip install -U pip wheel
COPY . /home/webapp/
USER root
