# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-14 04:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SFTPPublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Device name')),
                ('key_type', models.CharField(max_length=100, verbose_name='Key Type')),
                ('public_key', models.TextField(verbose_name='Public Key')),
                ('added', models.DateField(auto_now_add=True, verbose_name='Added')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
