# Generated by Django 4.2.2 on 2023-08-02 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0003_alter_institution_name_alter_projectacl_group_and_more"),
        (
            "tardis_portal",
            "0025_alter_datafileacl_group_alter_datafileacl_token_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDataClassification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classification",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Restricted"),
                            (25, "Sensitive"),
                            (50, "Internal"),
                            (100, "Public"),
                        ],
                        default=25,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_classification",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExperimentDataClassification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classification",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Restricted"),
                            (25, "Sensitive"),
                            (50, "Internal"),
                            (100, "Public"),
                        ],
                        default=25,
                    ),
                ),
                (
                    "experiment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_classification",
                        to="tardis_portal.experiment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DatasetDataClassification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classification",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Restricted"),
                            (25, "Sensitive"),
                            (50, "Internal"),
                            (100, "Public"),
                        ],
                        default=25,
                    ),
                ),
                (
                    "dataset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_classification",
                        to="tardis_portal.dataset",
                    ),
                ),
            ],
        ),
    ]
