# Generated by Django 3.2.7 on 2023-08-21 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tardis_portal', '0019_alter_userauthentication_authenticationmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.BigIntegerField(null=True)),
                ('files', models.BigIntegerField(null=True)),
                ('datasets', models.BigIntegerField(null=True)),
                ('experiments', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tardis_portal.facility')),
            ],
        ),
    ]
