# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 03:44
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openid_migration', '0001_initial'),
        ('tardis_portal', '0019_create_and_populate_new_acls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openidaclmigration',
            name='acl_id',
        ),
        migrations.AddField(
            model_name='openidaclmigration',
            name='acl_id',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='tardis_portal.ExperimentACL'),
        ),
    ]
