version: "2"
services:
  run:
    build:
      context: ..
      dockerfile: SemaphoreCI/Dockerfile-run
    image: mytardis/mytardis-run
  test:
    build:
      context: ..
      dockerfile: SemaphoreCI/Dockerfile-test
    image: mytardis/mytardis-test
    depends_on:
      - run
      - pg
      - mysql
    links:
      - pg
      - mysql
  pg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    command: --default-authentication-plugin=mysql_native_password
