# Generated by Django 3.2.5 on 2021-07-29 00:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstat',
            unique_together={('date', 'user', 'stat')},
        ),
    ]
