name: MyTardis CI tests
on: [push, pull_request]

jobs:
  build-docker:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build test docker image
        run: docker-compose -f docker-ci/docker-build.yml run builder
      - name: save image
        run: docker save mytardis/mytardis-base > /tmp/base-image.tar
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: base-image
          path: /tmp/base-image.tar

  test-on-sqlite:
    runs-on: ubuntu-20.04
    needs: build-docker
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: base-image
          path: /tmp
      - name: load image
        run: docker load < /tmp/base-image.tar
      - name: list images
        run: docker image ls -a

