name: MyTardis CI tests
on: [push, pull_request]

jobs:
  build-docker:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build test docker image
        run: docker-compose -f docker-ci/docker-build.yml run builder
      - name: list images
        run: docker image ls
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: base-image
          path: /tmp/base-image.tar

  test-on-sqlite:
    runs-on: ubuntu-20.04
    steps:
      - name: checout
        uses: actions/checkout@v2

